language: node_js

node_js:
  - "0.10"

script:
  - ./node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --browsers PhantomJS

before_script:
  - npm install -g bower codeclimate-test-reporter
  - npm install
  - bower install angular angular-mocks

after_script:
  - cat coverage/lcov.info | codeclimate

addons:
  code_climate:
    repo_token: bcdb10bb2c4dc0cb26430ba50da0bd9884c24393